version: 2.1

executors:
  node-browsers:
    docker:
      - image: cimg/node:16.15-browsers

jobs:
  build:
    executor: node-browsers
    parallelism: 2
    resource_class: small
    steps:
      - run:
          name: Check out previous test metadata
          command: |
            cat "${CIRCLE_INTERNAL_TASK_DATA}/circle-test-results/results.json" | jq .
      - checkout
      - run:
          name: NPM install
          command: npm install
      - run:
          name: Tests Using CIRCLE_NODE_INDEX
          command: bash test.sh
      - run:
          name: Showcase saved junit.xml
          command: |
            # we will note that for each <testcase>, the `file` attribute is missing
            cat www/junit.xml
      # - run:
      #     name: Modify junit.xml to add `file`
      #     command: |
      #       python3 www/xml_corrector.py
      # - run:
      #     name: Showcase modified junit.xml
      #     command: |
      #       cat www/junit.xml
      - store_test_results:
          path: www/junit.xml
      - store_artifacts:
          path: www/junit.xml
      - run:
          name: Debug Test Metadata
          command: |
            cat "${CIRCLE_INTERNAL_TASK_DATA}/circle-test-results/results.json" | jq "."

workflows:
  main:
    jobs:
      - build
