version: 2.1

executors:
  node-browsers:
    docker:
      - image: cimg/node:16.15-browsers
    working_directory: /mnt/ramdisk

jobs:
  build:
    executor: node-browsers
    parallelism: 2
    resource_class: small
    steps:
#       - run:
#           name: Check out previous test metadata
#           command: |
#             cat "${CIRCLE_INTERNAL_TASK_DATA}/circle-test-results/results.json" | jq .
      - checkout
      - attach_workspace:
          at: /mnt/ramdisk/
      - run:
          name: glob tests to verify
          command: |
            circleci tests glob "/mnt/ramdisk/**/*.test.js"
      - run:
          name: NPM install
          command: |
            npm install
            npx playwright install
      - run:
          name: Tests Using Glob/Split
          command: bash glob_split.sh
      - run:
          name: Showcase saved junit.xml
          command: |
            # we will note that for each <testcase>, the `file` attribute is missing
            cat www/junit.xml
      # turns out, Playwright comes with its own junit reporter.
      # it does not use the jest-junit library
      # so, Playwright's version does not come with adding file attribute.
      - run:
          name: Modify junit.xml to add `file`
          command: |
            python3 www/xml_corrector.py
      - run:
          name: Showcase modified junit.xml
          command: |
            cat www/junit.xml
      - store_test_results:
          path: www
      - store_artifacts:
          path: /mnt/ramdisk/www/junit.xml
#       - run:
#           name: Debug Test Metadata
#           command: |
#             cat "${CIRCLE_INTERNAL_TASK_DATA}/circle-test-results/results.json" | jq "."

workflows:
  main:
    jobs:
      - build
